### ISSUE TITLE
Crash Because Globed

### ISSUE THREAD

**Issue by JohnnyEnglish83** [flurrybun/colorful-icons#1]
When i exist from globed i got crash
(Android 64-bit) 

https://github.com/user-attachments/assets/83780211-2185-48ed-9e13-182b705fc84c

**Comment by flurrybun** [comment]
how did you even find this mod it hasn't been accepted to the index yet 😭

try downloading this version, it should be fixed now: https://github.com/flurrybun/colorful-icons/releases/download/v1.0.1/ninkaz.colorful-icons.geode

**Comment by JohnnyEnglish83** [comment]
> how did you even find this mod it hasn't been accepted to the index yet 😭
> 
> try downloading this version, it should be fixed now: https://github.com/flurrybun/colorful-icons/releases/download/v1.0.1/ninkaz.colorful-icons.geode

I Have Unverified Mods by user95401 🙂

+ Thanks So Much
